### ISSUE TITLE
Failed use chunk_id when append default setting true

### ISSUE THREAD

**Issue by wbchn** [fluent/fluent-plugin-webhdfs#26]
Fluentd running failed when setting using ${chunk_id} in path, but do not setting append to false.

How about fix this in `generate_path`:
```
    hdfs_path = if @append
                  path_format(chunk.key).gsub(CHUNK_ID_PLACE_HOLDER, '0')
                else
                  path_format(chunk.key).gsub(CHUNK_ID_PLACE_HOLDER, chunk_unique_id_to_str(chunk.unique_id))
                end
```

I am not sure it work fine or not.

**Comment by wbchn** [comment]
Other thing, I notice plugin setting `config_set_default :buffer_type, 'memory'`
but the [webhdfs page in fluentd](http://docs.fluentd.org/articles/out_webhdfs#buffertype) said default buffer type if `file`. 

By the way, does webhdfs plugin support file buffer? If supported, how setting file buffer path, using local path or hdfs path?

**Comment by tagomoris** [comment]
`chunk_id` is unique string between chunks. Each chunk has different chunk_id.
If you wanna append data into a file path, it should not contain `${chunk_id}`. Different chunk_id generate different path for each flushing.
It's the reason why `${chunk_id}` is ignored when `@append` is enabled.
