### ISSUE TITLE
Plugin lost file buffer when setting buffer type to file and split file by hourly

### ISSUE THREAD

**Issue by wbchn** [fluent/fluent-plugin-webhdfs#27]
First, I notice plugin setting `config_set_default :buffer_type, 'memory'`
but the [webhdfs page in fluentd](http://docs.fluentd.org/articles/out_webhdfs#buffertype) said default buffer type if `file`. 

Issue:
I hope split file by hourly, and split file with 1G limit:
```
## hdfs file will split by hourly
path /fluentd/__TAG__/__TAG__-%Y%m%d_%H-${hostname}-${chunk_id}.log
## disable append
append false
## using file buffer and chunk_limit is 1G
buffer_type file
buffer_path /mnt1/.fluentd_s3/__TAG__
buffer_chunk_limit 1G
flush_interval 1h
```

but I found when a new hour coming, last hour buffer which not came chunk_limit buffer file lost, the file buffer stored local, do not write to HDFS:
local buffer:
```
$ ll /mnt1/.fluentd_buffer/hdfs-flood*
-rw-r--r-- 1 root root 761827225 May 28 19:59 /mnt1/.fluentd_buffer/hdfs-flood.2015052819.b5172fa110175e555.log
-rw-r--r-- 1 root root 218389725 May 28 20:13 /mnt1/.fluentd_buffer/hdfs-flood.2015052820.b5172fdaac185fdbf.log
```
hdfs files:
```
$ hadoop fs -ls -R /fluentd/hdfs-flood
-rwxr-xr-x   1 hadoop supergroup 1073740925 2015-05-28 19:48 /fluentd/hdfs-flood/hdfs-flood-20150528_19-ip-172-10-1-100-5172f72f0e460de85172f72f0e460de8.log
-rwxr-xr-x   1 hadoop supergroup 1073740925 2015-05-28 19:52 /fluentd/hdfs-flood/hdfs-flood-20150528_19-ip-172-10-1-100-5172f82516163c435172f82516163c43.log
-rwxr-xr-x   1 hadoop supergroup 1073740925 2015-05-28 19:57 /fluentd/hdfs-flood/hdfs-flood-20150528_19-ip-172-10-1-100-5172f91aed4ddf635172f91aed4ddf63.log
-rwxr-xr-x   1 hadoop supergroup 1073740925 2015-05-28 20:04 /fluentd/hdfs-flood/hdfs-flood-20150528_20-ip-172-10-1-100-5172fabfe72fb52f5172fabfe72fb52f.log
-rwxr-xr-x   1 hadoop supergroup 1073740925 2015-05-28 20:08 /fluentd/hdfs-flood/hdfs-flood-20150528_20-ip-172-10-1-100-5172fbb42ea7c9605172fbb42ea7c960.log
```

The buffer file `/mnt1/.fluentd_s3/hdfs-flood.2015052819.b5172fa110175e555.log` do not flush to HDFS!

**Comment by tagomoris** [comment]
Once you specify `flush_interval`, `time_slice_wait` is ignored, and your chunk will be flushed after `flush_interval`(1 hour by your configuration) from chunk generation. (this is fluentd's normal behavior.)
So you should wait to see whether chunk object is successfully flushed or not until `20:57` for last chunk file.

Do you understand this behavior?

**Comment by wbchn** [comment]
I know it, even using `flush_interval` with default setting(default is 60s), the file buffer of last hour do not upload until 10 minute in new hour, like this:
`write a data(1) at 8:56, and the buffer file(buffer-2015052808.xxxx) lower than 1G at 8:59:59`

the data(1) in buffer flush data to hdfs until 9:11.

how about upload the buffer before new buffer using? I means flush data to hdfs in real time(less than 1min) and split file into 1G size.

**Comment by tagomoris** [comment]
Are you willing to write data per 1GB or per 1minute, right?
If so, you should configure like this:

* `append false`
* `path /path/to/dir/filename-including-minute.%Y%m%d_%H%M.${hostname}.${chunk_id}.log`
* `buffer_chunk_limit 1g`
* `time_slice_wait 1m`

If you wanna split files per hour with per-minute flush, you should enable `append`.

**Comment by wbchn** [comment]
Sorry, I made a mistake. As you said above, just add config `time_slice_wait 1m`, the file will write into per hour with max size limit 1G. 

The buffer(like data(1) which i referred) will flush to hdfs at 9:01

Thank you very much.

**Comment by tagomoris** [comment]
Good to hear that :smile:
