### ISSUE TITLE
out_webhdfs.rb's class changed from TimeSlicedOutput to Output

### ISSUE THREAD

**Issue by withsmilo** [fluent/fluent-plugin-webhdfs#50]
[This commit](https://github.com/fluent/fluent-plugin-webhdfs/commit/0b822df0a753a00b97f61abba5c9fec204b6e8e1#diff-628c1ade09277f948b0cbe967baa42adL11) changed out_webhdfs.rb's class from TimeSlicedOutput to Output. Is this right?

**Comment by repeatedly** [comment]
Write because this changes is for v0.14 API.

**Comment by withsmilo** [comment]
@repeatedly : Thank you for your rapid reply! :)
