### ISSUE TITLE
Kerberos Keytab example

### ISSUE THREAD

**Issue by jomach** [fluent/fluent-plugin-webhdfs#58]
Hi, Can someone give an example how to configure  this plugin to use a kerberos keytab and principal ? having just kerberos=true does not help a lot. thanks

**Comment by krithiga90** [comment]
Hi,

We are evaluating FluentD to ingest data into HDFS and we also have Kerberos based authentication. Could someone please elaborate on the Configuration for Kerberos based auth?

**Comment by jomach** [comment]
@krithiga90  I did not evaluate this further but I think it will get the configs from /etc/hadoop and there you will have the pfad to the keytab...

**Comment by repeatedly** [comment]
Currently, no support for keytab.
I just wrote a patch. Check this: https://github.com/fluent/fluent-plugin-webhdfs/pull/60

**Comment by jomach** [comment]
Thanks for the Patch.

**Comment by frencopei** [comment]
fluentd latest version support writing kerberos kafka?
